Revert "US3987 remove dependencies on jquery-migrate"
This reverts commit ad4df64116386c7dcab1d8efc49e8bc528d9ee9c.

Fixes error:

Error: Mismatched anonymous define() module: undefined
http://requirejs.org/docs/errors.html#mismatch